[workspace]
authors = ["ManifoldFR"]
channels = ["conda-forge"]
name = "nanoeigenpy"
description = "A support library for bindings between Eigen/C++ and Python, based on nanobind"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.9"
eigen = ">=3.3.1"

[build-dependencies]
nanobind = ">=2.5.0,<3"
cmake = ">=3.15"
cxx-compiler = ">=1.7"
ccache = ">=4.11.2"
ninja = ">=1.12.1"
pkg-config = ">=0.29.2"
git = ">=2.49.0"
doxygen = ">=1.13.2,<2"
